
# Параметры кирпича
BRICK_HEIGHT = 66
BRICK_STARTING_X = 250
BRICK_STARTING_Y = 300
SPEED_Y = 100
BRICK_WIDTH = 194

# Параметры экрана и пола
SCREEN_WIDTH = 640
SCREEN_HEIGHT = 1000
FLOOR_HEIGHT = SCREEN_HEIGHT - 120
BRICK_STOP_HEIGHT = FLOOR_HEIGHT - BRICK_HEIGHT

# Ось и циферки
AXIS_COLOR = (130, 100, 50)
LINE_WIDTH = 5
TICK_LENGTH = 15

# Параметры руки
HAND_STARTING_X = 320
HAND_STARTING_Y = -1
HAND_SPEED_X = 100
HAND_SPEED_Y = 20
HAND_ACCELERATION = 1
MAX_HAND_SPEED = 500
HAND_GRIP_POSITION_X = -55
HAND_GRIP_POSITION_Y = 200

# Физические константы
FPS = 60
G = 800
DELTA_T = 1/FPS

# Картинки
IMAGES_DIRECTORY = "source/images/"
WHITE_BRICK_FILENAME = IMAGES_DIRECTORY + "brick_white.png"
BACKGROUND_FILENAME = IMAGES_DIRECTORY + "wallpaper_cut.jpg"
FLOOR_FILENAME = IMAGES_DIRECTORY + "floor.png"
HAND_FILENAME = IMAGES_DIRECTORY + "lego_hand.png"

# Звуки
SOUND_DIRECTORY = "source/sounds/"
BACK_MUSIC_1 = SOUND_DIRECTORY + "Back_music_1.mp3"
BUM_1 = SOUND_DIRECTORY + "Bym_1.mp3"
